FROM        tychrestoff/debian:jessie-min
MAINTAINER  tychrestoff

RUN apt-get update && apt-get install -y --no-install-recommends \
    ca-certificates \
    curl \
    wget \
 && rm -rf /var/lib/apt/lists/*
